image: gcc

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job-master:
  only:
    - master
  stage: build
  script:
    - apt-get update
    - apt-get -y install python3 python3-pip gcc-9 g++-9 libboost-math-dev
    - python3 -m pip install -U setuptools numpy Cython twine scipy Sphinx pqdm sphinx_rtd_theme
    - bash run.sh clean build test

build-job-dev:
  only:
    - dev
  when: manual
  stage: build
  script:
    - apt-get update
    - apt-get -y install python3 python3-pip gcc-9 g++-9 libboost-math-dev
    - python3 -m pip install -U setuptools numpy Cython twine scipy Sphinx pqdm sphinx_rtd_theme
    - bash run.sh clean build test
