image: gcc

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

before_script:
  - apt-get update
  - apt-get -y install python3 python3-pip gcc-9 g++-9
  - python3 -m pip install -U setuptools numpy Cython twine
  - python3 -c $'import os, cython; f = open(os.path.join(os.path.dirname(cython.__file__), "Cython", "Compiler", "Parsing.py"), "r+"); script = f.read(); script2 = script.replace("\'+\', \'-\', \'*\', \'/\', \'%\',\\n", "\'+\', \'-\', \'*\', \'/\', \'%\',\\n    \'+=\', \'-=\', \'*=\', \'/=\', \'&=\', \'|=\',\\n"); f.seek(0); f.write(script2); f.truncate(); f.close()'

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - bash run.sh clean build test
